/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Garden, GardenArea, Plant, PlantCategory, PlantMarker } from './types';

export const categories: PlantCategory[] = [
  { id: 'cat-1', name: 'Trees', description: 'Large perennial woody plants', color: '#16a34a' },
  { id: 'cat-2', name: 'Medicinal', description: 'Plants with healing properties', color: '#059669' },
  { id: 'cat-3', name: 'Flowers', description: 'Ornamental flowering plants', color: '#db2777' },
  { id: 'cat-4', name: 'Palms', description: 'Tropical and subtropical trees', color: '#0d9488' },
  { id: 'cat-5', name: 'Shrubs', description: 'Small to medium-sized woody plants', color: '#4d7c0f' },
];

export const gardens: Garden[] = [
  {
    id: 'vbf',
    name: 'Viswanadhapalli Botanical Garden',
    code: 'VBF',
    location: 'North Campus, GITAM Visakhapatnam',
    description: 'A sprawling 50-acre botanical sanctuary dedicated to conservation and education, featuring over 130 tagged species.',
    coverImage: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 1,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'sac',
    name: 'Sir Arthur Cotton Garden',
    code: 'SAC',
    location: 'Engineering Block',
    description: 'Dedicated to the irrigation pioneer, this garden features aquatic plants and efficient landscape designs.',
    coverImage: 'https://images.unsplash.com/photo-1598901861713-a4ad16a7d72e?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 2,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'phg',
    name: 'Pharmacy Garden',
    code: 'PHG',
    location: 'Pharmacy Block',
    description: 'A specialized collection of medicinal and aromatic plants used for pharmaceutical research.',
    coverImage: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 3,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const areas: GardenArea[] = [
  {
    id: 'a-vbf-1',
    gardenId: 'vbf',
    name: 'Palm Grove',
    code: 'VBF-PZ',
    description: 'A majestic collection of tropical and subtropical palms, including rare endemic species.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 1,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a-vbf-2',
    gardenId: 'vbf',
    name: 'Medicinal Zone',
    code: 'VBF-MZ',
    description: 'Featuring traditional healing plants like Neem, Tulsi, and Aloe Vera used in ancient medicine.',
    imageUrl: 'https://images.unsplash.com/photo-1599591037488-8a3064d5c9cc?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 2,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a-vbf-3',
    gardenId: 'vbf',
    name: 'Arboretum',
    code: 'VBF-ARB',
    description: 'A vast area dedicated to diverse native and exotic tree species, providing a rich canopy for campus wildlife.',
    imageUrl: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&q=80&w=1200',
    status: 'active',
    displayOrder: 3,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const plants: Plant[] = [
  {
    id: 'p-neem',
    categoryId: 'cat-2',
    commonName: 'Neem',
    botanicalName: 'Azadirachta indica',
    scientificName: 'Azadirachta indica',
    family: 'Meliaceae',
    shortDescription: 'The "Village Pharmacy" tree, essential in traditional medicine.',
    description: 'Native to the Indian subcontinent, the Neem tree is a cornerstone of traditional medicine. Every part of the tree – leaves, bark, and seeds – possesses potent antimicrobial and anti-inflammatory properties.',
    benefits: 'Antiseptic, blood purifier, and organic pesticide.',
    careInstructions: 'Drought tolerant once established. Prefers well-drained soil and full sun.',
    sunlightRequirement: 'full sun',
    waterRequirement: 'low',
    soilType: 'All types, well-drained',
    temperature: '20°C - 35°C',
    humidity: 'Low to moderate',
    averageHeight: '15-20 meters',
    growthRate: 'Fast',
    floweringSeason: 'Spring',
    nativeRegion: 'India, Myanmar',
    primaryImage: 'https://images.unsplash.com/photo-1630138222955-4089c968f9a2?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-tulsi',
    categoryId: 'cat-2',
    commonName: 'Holy Basil (Tulsi)',
    botanicalName: 'Ocimum tenuiflorum',
    scientificName: 'Ocimum sanctum',
    family: 'Lamiaceae',
    shortDescription: 'The "Queen of Herbs", revered for its medicinal and spiritual value.',
    description: 'Tulsi is a sacred plant in Hindu culture and a powerhouse in Ayurveda. It is an adaptogen, helping the body manage stress and promoting mental clarity.',
    benefits: 'Immune booster, stress reliever, and treats respiratory ailments.',
    careInstructions: 'Needs regular watering and well-drained soil. Pinch tips for bushier growth.',
    sunlightRequirement: 'full sun',
    waterRequirement: 'moderate',
    soilType: 'Rich loamy soil',
    temperature: '15°C - 30°C',
    humidity: 'Moderate',
    averageHeight: '30-60 cm',
    growthRate: 'Moderate',
    floweringSeason: 'Summer',
    nativeRegion: 'Tropical Asia',
    primaryImage: 'https://images.unsplash.com/photo-1603517452331-5975f7823351?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p-peepal',
    categoryId: 'cat-1',
    commonName: 'Peepal Tree',
    botanicalName: 'Ficus religiosa',
    scientificName: 'Ficus religiosa',
    family: 'Moraceae',
    shortDescription: 'Sacred fig tree known for its unique heart-shaped leaves.',
    description: 'A large dry season-deciduous or semi-evergreen tree. It is sacred to Hindus and Buddhists. It can live for over 1,000 years.',
    benefits: 'Air purifier, treats asthma and digestive issues.',
    careInstructions: 'Requires ample space. Very hardy once established.',
    sunlightRequirement: 'full sun',
    waterRequirement: 'moderate',
    soilType: 'Deep, well-drained soil',
    averageHeight: '30 meters',
    nativeRegion: 'Indian Subcontinent',
    primaryImage: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&q=80&w=800',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const markers: PlantMarker[] = [
  { id: 'm-vbf-1', areaId: 'a-vbf-2', plantId: 'p-neem', x: 30, y: 40, status: 'active' },
  { id: 'm-vbf-2', areaId: 'a-vbf-2', plantId: 'p-tulsi', x: 70, y: 25, status: 'active' },
  { id: 'm-vbf-3', areaId: 'a-vbf-3', plantId: 'p-peepal', x: 50, y: 50, status: 'active' },
];
